[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true

[package]
format = '[$symbol$version]($style) '

[python]
pyenv_version_name = true
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
