[dart]
format = '[$symbol($version )]($style)'

[elm]
format = '[$symbol($version )]($style) '
[env_var.WINDOW]
format = '$symbol[$env_value]($style) '
style = 'green'
symbol = '🖥️'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = false

[haskell]
format = '[$symbol($version )]($style)'

[hg_branch]
disabled = false
format = '[$symbol$branch(:$topic)]($style) '

[java]
format = '[$symbol($version )]($style)'
[lua]
format = '[$symbol($version )]($style)'

[nodejs]
detect_extensions = ['mjs', 'cjs', 'ts', 'mts', 'cts']
format = '[$symbol($version )]($style)'
symbol = '🥔 '

[package]
format = '[$symbol$version]($style) '

[python]
pyenv_version_name = true
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
